// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#include "../ui.h"

void ui_menu_screen_init(void)
{
    ui_menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_menu, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_menu, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_menu);
    lv_obj_set_width(ui_Panel1, 325);
    lv_obj_set_height(ui_Panel1, 188);
    lv_obj_set_x(ui_Panel1, -2);
    lv_obj_set_y(ui_Panel1, 12);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xA1D7F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifi = lv_imgbtn_create(ui_Panel1);
    lv_imgbtn_set_src(ui_wifi, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_wifi_png, NULL);
    lv_obj_set_height(ui_wifi, 48);
    lv_obj_set_width(ui_wifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_wifi, 116);
    lv_obj_set_y(ui_wifi, 32);
    lv_obj_set_align(ui_wifi, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_wifi, lv_color_hex(0x93EFD5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_camere = lv_imgbtn_create(ui_Panel1);
    lv_imgbtn_set_src(ui_camere, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_cemare_png, NULL);
    lv_obj_set_height(ui_camere, 48);
    lv_obj_set_width(ui_camere, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_camere, 118);
    lv_obj_set_y(ui_camere, -57);
    lv_obj_set_align(ui_camere, LV_ALIGN_CENTER);

    ui_mp3 = lv_imgbtn_create(ui_Panel1);
    lv_imgbtn_set_src(ui_mp3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_mp3_png, NULL);
    lv_obj_set_height(ui_mp3, 50);
    lv_obj_set_width(ui_mp3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_mp3, 6);
    lv_obj_set_y(ui_mp3, -57);
    lv_obj_set_align(ui_mp3, LV_ALIGN_CENTER);

    ui_sdcard = lv_imgbtn_create(ui_Panel1);
    lv_imgbtn_set_src(ui_sdcard, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_sd_png, NULL);
    lv_obj_set_height(ui_sdcard, 49);
    lv_obj_set_width(ui_sdcard, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_sdcard, -104);
    lv_obj_set_y(ui_sdcard, -60);
    lv_obj_set_align(ui_sdcard, LV_ALIGN_CENTER);

    ui_bluetooth = lv_imgbtn_create(ui_Panel1);
    lv_imgbtn_set_src(ui_bluetooth, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_bluetooth_png, NULL);
    lv_obj_set_height(ui_bluetooth, 48);
    lv_obj_set_width(ui_bluetooth, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_bluetooth, -104);
    lv_obj_set_y(ui_bluetooth, 30);
    lv_obj_set_align(ui_bluetooth, LV_ALIGN_CENTER);

    ui_weather = lv_imgbtn_create(ui_Panel1);
    lv_imgbtn_set_src(ui_weather, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_weather_png, NULL);
    lv_obj_set_height(ui_weather, 48);
    lv_obj_set_width(ui_weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_weather, 6);
    lv_obj_set_y(ui_weather, 31);
    lv_obj_set_align(ui_weather, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_weather, lv_color_hex(0x3EADD5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelweather = ui_Small_Label_create(ui_menu);
    lv_obj_set_x(ui_Labelweather, 4);
    lv_obj_set_y(ui_Labelweather, 196);
    lv_label_set_text(ui_Labelweather, "Weather");
    lv_obj_set_style_text_font(ui_Labelweather, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSD = ui_Small_Label_create(ui_menu);
    lv_obj_set_x(ui_LabelSD, -107);
    lv_obj_set_y(ui_LabelSD, 101);
    lv_label_set_text(ui_LabelSD, "SD");

    ui_LabelMP3 = ui_Small_Label_create(ui_menu);
    lv_obj_set_x(ui_LabelMP3, -1);
    lv_obj_set_y(ui_LabelMP3, 103);
    lv_label_set_text(ui_LabelMP3, "MP3");

    ui_LabelCamera = ui_Small_Label_create(ui_menu);
    lv_obj_set_x(ui_LabelCamera, 117);
    lv_obj_set_y(ui_LabelCamera, 101);
    lv_label_set_text(ui_LabelCamera, "Camera");

    ui_LabelBle = ui_Small_Label_create(ui_menu);
    lv_obj_set_x(ui_LabelBle, -105);
    lv_obj_set_y(ui_LabelBle, 191);
    lv_label_set_text(ui_LabelBle, "BlueTooth");

    ui_LabelWIFI = ui_Small_Label_create(ui_menu);
    lv_obj_set_x(ui_LabelWIFI, 117);
    lv_obj_set_y(ui_LabelWIFI, 195);
    lv_label_set_text(ui_LabelWIFI, "WiFI");

    ui_Panel2 = lv_obj_create(ui_menu);
    lv_obj_set_width(ui_Panel2, 322);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, -3);
    lv_obj_set_y(ui_Panel2, -106);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_menu);
    lv_img_set_src(ui_Image5, &ui_img_bluesamll_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image5, 114);
    lv_obj_set_y(ui_Image5, -106);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_menu);
    lv_img_set_src(ui_Image6, &ui_img_wifi_small_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image6, 144);
    lv_obj_set_y(ui_Image6, -106);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_mp3, ui_event_mp3, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_weather, ui_event_weather, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_camere, camera_event_handler, LV_EVENT_CLICKED, NULL);
}
