// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.6
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_H
#define _SMART_GADGET_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"

void upanim_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void sec_Animation(lv_obj_t * TargetObject, int delay);
void scrolldot_Animation(lv_obj_t * TargetObject, int delay);

// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
void ui_event_Splash(lv_event_t * e);
extern lv_obj_t * ui_Splash;
extern lv_obj_t * ui_Demo;
extern lv_obj_t * ui_Smart_Gadget;
extern lv_obj_t * ui_SLS_Logo;
// CUSTOM VARIABLES

// SCREEN: ui_menu
void ui_menu_screen_init(void);
extern lv_obj_t * ui_menu;
extern lv_obj_t * ui_Scrolldots;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_wifi;
extern lv_obj_t * ui_camere;
void ui_event_mp3(lv_event_t * e);
extern lv_obj_t * ui_mp3;
extern lv_obj_t * ui_sdcard;
extern lv_obj_t * ui_bluetooth;
void ui_event_weather(lv_event_t * e);
extern lv_obj_t * ui_weather;
// CUSTOM VARIABLES

// SCREEN: ui_Music_Player
void ui_Music_Player_screen_init(void);
extern lv_obj_t * ui_Music_Player;
extern lv_obj_t * ui_Album;
extern lv_obj_t * ui_Play_btn;
extern lv_obj_t * ui_Play;
extern lv_obj_t * ui_Backward;
extern lv_obj_t * ui_Forward;
extern lv_obj_t * ui_Scrolldots3;
extern lv_obj_t * ui_Dropdown1;
void ui_event_back(lv_event_t * e);
extern lv_obj_t * ui_back;
// CUSTOM VARIABLES

// SCREEN: ui_Weather
void ui_Weather_screen_init(void);
void ui_event_Weather(lv_event_t * e);
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_Pary_Cloud;
extern lv_obj_t * ui_New_York;
extern lv_obj_t * ui_Cloud;
extern lv_obj_t * ui_Celsius;
extern lv_obj_t * ui_Weather_Icons;
extern lv_obj_t * ui_w1;
extern lv_obj_t * ui_;
extern lv_obj_t * ui_w3;
extern lv_obj_t * ui_W1_Num;
extern lv_obj_t * ui_W2_Num;
extern lv_obj_t * ui_W3_Num;
extern lv_obj_t * ui_Scrolldots4;
void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_sls_logo_png);    // assets/sls_logo.png
LV_IMG_DECLARE(ui_img_pattern_png);    // assets/pattern.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_cemare_png);    // assets/cemare.png
LV_IMG_DECLARE(ui_img_mp3_png);    // assets/MP3.png
LV_IMG_DECLARE(ui_img_sd_png);    // assets/SD.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/bluetooth.png
LV_IMG_DECLARE(ui_img_weather_png);    // assets/weather.png
LV_IMG_DECLARE(ui_img_album_png);    // assets/album.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_backward_png);    // assets/backward.png
LV_IMG_DECLARE(ui_img_forward_png);    // assets/forward.png
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_cloud_png);    // assets/cloud.png
LV_IMG_DECLARE(ui_img_weather_1_png);    // assets/weather_1.png
LV_IMG_DECLARE(ui_img_weather_2_png);    // assets/weather_2.png
LV_IMG_DECLARE(ui_img_weather_3_png);    // assets/weather_3.png
LV_IMG_DECLARE(ui_img_chatbox2_png);    // assets/chatbox2.png

// FONTS
LV_FONT_DECLARE(ui_font_Number);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
